CREATE OR REPLACE FUNCTION "dbo"."CLG_adm_sectionallotment_change_promotion_yearloss"(
    "p_ASMAY_Id" TEXT,
    "p_AMB_Id" TEXT,
    "p_AMCO_Id" TEXT,
    "p_AMSE_Id" TEXT,
    "p_mi_id" TEXT
)
RETURNS TABLE(
    "amcsT_FirstName" VARCHAR,
    "amcsT_MiddleName" VARCHAR,
    "amcsT_LastName" VARCHAR,
    "amcsT_AdmNo" VARCHAR,
    "AMCST_Id" BIGINT,
    "MI_Id" BIGINT,
    "ASMAY_Id" BIGINT,
    "AMB_Id" BIGINT,
    "AMCO_Id" BIGINT,
    "AMSE_Id" BIGINT,
    "ACMS_Id" BIGINT,
    "AMCST_SOL" VARCHAR,
    "AMCST_Date" TIMESTAMP,
    "AMCST_Sex" VARCHAR,
    "AMCST_DOB" TIMESTAMP,
    "AMCST_DOB_Words" VARCHAR,
    "AMCST_Age" INTEGER,
    "AMCST_BloodGroup" VARCHAR,
    "AMCST_MotherTongue" VARCHAR,
    "AMCST_BirthCertNo" VARCHAR,
    "IVRMMR_Id" BIGINT,
    "IMCC_Id" BIGINT,
    "IMC_Id" BIGINT,
    "AMCST_StudentSubCaste" VARCHAR,
    "AMCST_PerStreet" VARCHAR,
    "AMCST_PerArea" VARCHAR,
    "AMCST_PerCity" VARCHAR,
    "AMCST_PerState" VARCHAR,
    "IVRMMC_Id" BIGINT,
    "AMCST_PerPincode" BIGINT,
    "AMCST_ConStreet" VARCHAR,
    "AMCST_ConArea" VARCHAR,
    "AMCST_ConCity" VARCHAR,
    "AMCST_ConState" VARCHAR,
    "AMCST_ConCountryId" BIGINT,
    "AMCST_ConPincode" BIGINT,
    "AMCST_AadharNo" BIGINT,
    "AMCST_MobileNo" BIGINT,
    "AMCST_emailId" VARCHAR,
    "AMCST_FatherName" VARCHAR,
    "AMCST_FatherSurname" VARCHAR,
    "AMCST_FatherAadharNo" BIGINT,
    "AMCST_FatherEducation" VARCHAR,
    "AMCST_FatherOccupation" VARCHAR,
    "AMCST_FatherOfficeAdd" VARCHAR,
    "AMCST_FatherDesignation" VARCHAR,
    "AMCST_FatherMonIncome" DECIMAL,
    "AMCST_FatherMobleNo" BIGINT,
    "AMCST_FatheremailId" VARCHAR,
    "AMCST_MotherName" VARCHAR,
    "AMCST_MotherSurname" VARCHAR,
    "AMCST_MotherAadharNo" BIGINT,
    "AMCST_MotherEducation" VARCHAR,
    "AMCST_MotherOccupation" VARCHAR,
    "AMCST_MotherOfficeAdd" VARCHAR,
    "AMCST_MotherDesignation" VARCHAR,
    "AMCST_MotherMonIncome" DECIMAL,
    "AMCST_MotherMobleNo" BIGINT,
    "AMCST_MotheremailId" VARCHAR,
    "AMCST_TotalIncome" DECIMAL,
    "AMCST_BPLCardFlag" BOOLEAN,
    "AMCST_BPLCardNo" VARCHAR,
    "AMCST_HostelReqdFlag" BOOLEAN,
    "AMCST_TransportReqdFlag" BOOLEAN,
    "AMCST_GymReqdFlag" BOOLEAN,
    "AMCST_ECSFlag" BOOLEAN,
    "AMCST_PaymentFlag" INTEGER,
    "AMCST_AmountPaid" DECIMAL,
    "AMCST_PaymentType" VARCHAR,
    "AMCST_PaymentDate" TIMESTAMP,
    "AMCST_ReceiptNo" VARCHAR,
    "AMCST_ActiveFlag" BOOLEAN,
    "AMCST_PhoneNo" BIGINT,
    "AMCST_PerState_Urban_Rural" VARCHAR,
    "AMCST_ConState_Urban_Rural" VARCHAR,
    "AMCST_Noofsisters" INTEGER,
    "AMCST_Noofbrothers" INTEGER,
    "AMCST_NoOfElderSisters" INTEGER,
    "AMCST_NoOfYoungerSisters" INTEGER,
    "AMCST_NoOfElderBrothers" INTEGER,
    "AMCST_NoOfYoungerBrothers" INTEGER,
    "AMCST_lastschoolattended" VARCHAR,
    "AMCST_Tcflag" BOOLEAN,
    "AMCST_CreatedBy" BIGINT,
    "AMCST_UpdatedBy" BIGINT,
    "CreatedDate" TIMESTAMP,
    "UpdatedDate" TIMESTAMP
) 
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        a."amcsT_FirstName", 
        a."amcsT_MiddleName",
        a."amcsT_LastName",
        a."amcsT_AdmNo",
        a."AMCST_Id",
        a."MI_Id",
        a."ASMAY_Id",
        a."AMB_Id",
        a."AMCO_Id",
        a."AMSE_Id",
        a."ACMS_Id",
        a."AMCST_SOL",
        a."AMCST_Date",
        a."AMCST_Sex",
        a."AMCST_DOB",
        a."AMCST_DOB_Words",
        a."AMCST_Age",
        a."AMCST_BloodGroup",
        a."AMCST_MotherTongue",
        a."AMCST_BirthCertNo",
        a."IVRMMR_Id",
        a."IMCC_Id",
        a."IMC_Id",
        a."AMCST_StudentSubCaste",
        a."AMCST_PerStreet",
        a."AMCST_PerArea",
        a."AMCST_PerCity",
        a."AMCST_PerState",
        a."IVRMMC_Id",
        a."AMCST_PerPincode",
        a."AMCST_ConStreet",
        a."AMCST_ConArea",
        a."AMCST_ConCity",
        a."AMCST_ConState",
        a."AMCST_ConCountryId",
        a."AMCST_ConPincode",
        a."AMCST_AadharNo",
        a."AMCST_MobileNo",
        a."AMCST_emailId",
        a."AMCST_FatherName",
        a."AMCST_FatherSurname",
        a."AMCST_FatherAadharNo",
        a."AMCST_FatherEducation",
        a."AMCST_FatherOccupation",
        a."AMCST_FatherOfficeAdd",
        a."AMCST_FatherDesignation",
        a."AMCST_FatherMonIncome",
        a."AMCST_FatherMobleNo",
        a."AMCST_FatheremailId",
        a."AMCST_MotherName",
        a."AMCST_MotherSurname",
        a."AMCST_MotherAadharNo",
        a."AMCST_MotherEducation",
        a."AMCST_MotherOccupation",
        a."AMCST_MotherOfficeAdd",
        a."AMCST_MotherDesignation",
        a."AMCST_MotherMonIncome",
        a."AMCST_MotherMobleNo",
        a."AMCST_MotheremailId",
        a."AMCST_TotalIncome",
        a."AMCST_BPLCardFlag",
        a."AMCST_BPLCardNo",
        a."AMCST_HostelReqdFlag",
        a."AMCST_TransportReqdFlag",
        a."AMCST_GymReqdFlag",
        a."AMCST_ECSFlag",
        a."AMCST_PaymentFlag",
        a."AMCST_AmountPaid",
        a."AMCST_PaymentType",
        a."AMCST_PaymentDate",
        a."AMCST_ReceiptNo",
        a."AMCST_ActiveFlag",
        a."AMCST_PhoneNo",
        a."AMCST_PerState_Urban_Rural",
        a."AMCST_ConState_Urban_Rural",
        a."AMCST_Noofsisters",
        a."AMCST_Noofbrothers",
        a."AMCST_NoOfElderSisters",
        a."AMCST_NoOfYoungerSisters",
        a."AMCST_NoOfElderBrothers",
        a."AMCST_NoOfYoungerBrothers",
        a."AMCST_lastschoolattended",
        a."AMCST_Tcflag",
        a."AMCST_CreatedBy",
        a."AMCST_UpdatedBy",
        a."CreatedDate",
        a."UpdatedDate"
    FROM "CLG"."Adm_Master_College_Student" a 
    LEFT JOIN "CLG"."Adm_College_Yearly_Student" dict ON dict."AMCST_Id" = a."AMCST_Id" 
    WHERE a."AMCST_ActiveFlag" = true 
        AND dict."AMCST_Id" IS NULL 
        AND a."ASMAY_Id"::TEXT = "p_ASMAY_Id" 
        AND a."AMB_Id"::TEXT = "p_AMB_Id" 
        AND a."AMCO_Id"::TEXT = "p_AMCO_Id" 
        AND a."AMSE_Id"::TEXT = "p_AMSE_Id" 
        AND a."MI_Id"::TEXT = "p_mi_id";
END;
$$;