CREATE OR REPLACE FUNCTION "Employee_Profile_Report"(
    p_MI_Id INT,
    p_HRME_Id INT
)
RETURNS TABLE(
    "HRME_Id" INT,
    "MI_Id" INT,
    "HRMET_Id" INT,
    "HRMGT_Id" INT,
    "HRMGT_EmployeeGroupType" VARCHAR,
    "HRMD_Id" INT,
    "HRMD_DepartmentName" VARCHAR,
    "HRMDES_Id" INT,
    "HRMDES_DesignationName" VARCHAR,
    "HRMG_Id" INT,
    "HRME_EmployeeFirstName" VARCHAR,
    "HRME_EmployeeMiddleName" VARCHAR,
    "HRME_EmployeeLastName" VARCHAR,
    "HRME_EmployeeCode" VARCHAR,
    "HRME_BiometricCode" VARCHAR,
    "HRME_RFCardId" VARCHAR,
    "HRME_FatherName" VARCHAR,
    "HRME_MotherName" VARCHAR,
    "HRME_DOB" TIMESTAMP,
    "HRME_DOJ" TIMESTAMP,
    "HRME_ExpectedRetirementDate" TIMESTAMP,
    "HRME_PFDate" TIMESTAMP,
    "HRME_ESIDate" TIMESTAMP,
    "HRME_MobileNo" VARCHAR,
    "HRME_EmailId" VARCHAR,
    "HRME_BloodGroup" VARCHAR,
    "HRME_PaymentType" VARCHAR,
    "HRME_BankAccountNo" VARCHAR,
    "HRME_PFApplicableFlag" BOOLEAN,
    "HRME_PFMaxFlag" BOOLEAN,
    "HRME_PFFixedFlag" BOOLEAN,
    "HRME_PFAccNo" VARCHAR,
    "HRME_ESIAccNo" VARCHAR,
    "HRME_GratuityAccNo" VARCHAR,
    "HRME_ESIApplicableFlag" BOOLEAN,
    "HRME_Photo" TEXT,
    "HRME_LeftFlag" BOOLEAN,
    "HRME_DOL" TIMESTAMP,
    "HRME_LeavingReason" VARCHAR,
    "HRME_Height" NUMERIC,
    "HRME_HeightUOM" VARCHAR,
    "HRME_Weight" NUMERIC,
    "HRME_WeightUOM" VARCHAR,
    "HRME_IdentificationMark" VARCHAR,
    "HRME_ApprovalNo" VARCHAR,
    "HRME_PANCardNo" VARCHAR,
    "HRME_AadharCardNo" VARCHAR,
    "HRME_SubstituteFlag" BOOLEAN,
    "HRME_NationalSSN" VARCHAR,
    "HRME_SalaryType" VARCHAR,
    "HRME_EmployeeOrder" INT
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        a."HRME_Id",
        a."MI_Id",
        a."HRMET_Id",
        a."HRMGT_Id",
        b."HRMGT_EmployeeGroupType",
        a."HRMD_Id",
        d."HRMD_DepartmentName",
        a."HRMDES_Id",
        c."HRMDES_DesignationName",
        a."HRMG_Id",
        a."HRME_EmployeeFirstName",
        a."HRME_EmployeeMiddleName",
        a."HRME_EmployeeLastName",
        a."HRME_EmployeeCode",
        a."HRME_BiometricCode",
        a."HRME_RFCardId",
        a."HRME_FatherName",
        a."HRME_MotherName",
        a."HRME_DOB",
        a."HRME_DOJ",
        a."HRME_ExpectedRetirementDate",
        a."HRME_PFDate",
        a."HRME_ESIDate",
        a."HRME_MobileNo",
        a."HRME_EmailId",
        a."HRME_BloodGroup",
        a."HRME_PaymentType",
        a."HRME_BankAccountNo",
        a."HRME_PFApplicableFlag",
        a."HRME_PFMaxFlag",
        a."HRME_PFFixedFlag",
        a."HRME_PFAccNo",
        a."HRME_ESIAccNo",
        a."HRME_GratuityAccNo",
        a."HRME_ESIApplicableFlag",
        a."HRME_Photo",
        a."HRME_LeftFlag",
        a."HRME_DOL",
        a."HRME_LeavingReason",
        a."HRME_Height",
        a."HRME_HeightUOM",
        a."HRME_Weight",
        a."HRME_WeightUOM",
        a."HRME_IdentificationMark",
        a."HRME_ApprovalNo",
        a."HRME_PANCardNo",
        a."HRME_AadharCardNo",
        a."HRME_SubstituteFlag",
        a."HRME_NationalSSN",
        a."HRME_SalaryType",
        a."HRME_EmployeeOrder"
    FROM "HR_Master_Employee" a
    INNER JOIN "HR_Master_GroupType" b ON a."HRMGT_Id" = b."HRMGT_Id"
    INNER JOIN "HR_Master_Department" d ON a."HRMD_Id" = d."HRMD_Id"
    INNER JOIN "HR_Master_Designation" c ON a."HRMDES_Id" = c."HRMDES_Id"
    INNER JOIN "IVRM_Master_Gender" e ON a."IVRMMG_Id" = e."IVRMMG_Id"
    INNER JOIN "IVRM_Master_Caste" f ON a."CasteId" = f."IMC_Id"
    INNER JOIN "IVRM_Master_Religion" g ON a."ReligionId" = g."IVRMMR_Id"
    WHERE a."MI_Id" = p_MI_Id
        AND a."HRME_Id" = p_HRME_Id;
END;
$$;