CREATE OR REPLACE FUNCTION "dbo"."CLG_Alumini_Students_Insert"(
    p_MI_Id bigint,
    p_ASMAY_Id bigint,
    p_AMCST_Id bigint
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    -- Exec [CLG_Alumini_Students_Insert] 18,67,887

    DROP TABLE IF EXISTS "ALU_M_clg_student_Temp";

    CREATE TEMP TABLE "ALU_M_clg_student_Temp" AS
    SELECT 
        "MI_Id",
        AMCS."AMCST_Id",
        AMCS."AMCO_Id" as "AMCO_JOIN_Id",
        AMCS."AMB_Id" as "AMB_JOIN_Id",
        AMCS."AMSE_Id" as "AMSE_JOIN_Id",
        AMCS."ASMAY_Id" as "ASMAY_Id_Join",
        ASYS."AMB_Id" as "AMB_Id_Left",
        ASYS."AMCO_Id" as "AMCO_Left_Id",
        ASYS."AMSE_Id" as "AMSE_Id_Left",
        ASYS."ASMAY_Id" as "ASMAY_Id_Left",
        "AMCST_FirstName" as "ALCMST_FirstName",
        "AMCST_MiddleName" as "ALCMST_MiddleName",
        "AMCST_LastName" as "ALCMST_LastName",
        "AMCST_Date" as "ALCMST_Date",
        "AMCST_RegistrationNo" as "ALCMST_RegistrationNo",
        "AMCST_AdmNo" as "ALCMST_AdmNo",
        "AMCST_Sex" as "ALCMST_Sex",
        "AMCST_DOB" as "ALCMST_DOB",
        AMCS."AMCST_DOBin_words" as "ALCMST_DOBinwords",
        "AMCST_Age" as "ALCMST_Age",
        0 as "ASMCL_Id_Join",
        0 as "ASMCL_Id_Left",
        "AMCST_BloodGroup" as "ALCMST_BloodGroup",
        "AMCST_MotherTongue" as "ALCMST_MotherTongue",
        "AMCST_MotherTongue" as "ALCMST_HomeLaguage",
        "AMCST_BirthCertNO" as "ALCMST_BirthCertNo",
        "IVRMMR_Id",
        "IMCC_Id",
        "IMC_Id" as "IMC_Id",
        AMCS."AMCST_StudentSubCaste" as "ALCMST_StudentSubCaste",
        "AMCST_PerStreet" as "ALCMST_PerStreet",
        "AMCST_PerArea" as "ALCMST_PerArea",
        "AMCST_PerCity" as "ALCMST_PerCity",
        "AMCST_PerAdd3" as "ALCMST_PerAdd3",
        "AMCST_PerState" as "ALCMST_PerState",
        AMCS."IVRMMC_Id" as "IVRMMC_Id",
        "AMCST_PerPincode" as "ALCMST_PerPincode",
        "AMCST_ConStreet" as "ALCMST_ConStreet",
        "AMCST_ConArea" as "ALCMST_ConArea",
        (COALESCE("AMCST_ConStreet",'') || '' || COALESCE("AMCST_ConArea",'') || '' || COALESCE("AMCST_ConCity",'')) as "ALCMST_ConAdd3",
        "AMCST_ConCity" as "ALCMST_ConCity",
        '' as "ALCMST_Village",
        '' as "ALCMST_Taluk",
        '' as "ALCMST_District",
        "AMCST_ConState" as "ALCMST_ConState",
        "AMCST_ConCountryId" as "ALCMST_ConCountryId",
        CAST("AMCST_ConPincode" as bigint) as "ALCMST_ConPincode",
        "AMCST_AadharNo" as "ALCMST_AadharNo",
        "AMCST_StuBankAccNo" as "ALCMST_StuBankAccNo",
        '' as "ALCMST_StudentPANCard",
        AMCS."AMCST_MotherBankIFSCCode" as "ALCMST_StuBankIFSCCode",
        "AMCST_StuCasteCertiNo" as "ALCMST_StuCasteCertiNo",
        "AMCST_MobileNo" as "ALCMST_MobileNo",
        "AMCST_emailId" as "ALCMST_emailId",
        "AMCST_FatherAliveFlag" as "ALCMST_FatherAliveFlag",
        "AMCST_FatherName" as "ALCMST_FatherName",
        "AMCST_FatherAadharNo" as "ALCMST_FatherAadharNo",
        "AMCST_FatherSurname" as "ALCMST_FatherSurname",
        "AMCST_FatherEducation" as "ALCMST_FatherEducation",
        "AMCST_FatherOccupation" as "ALCMST_FatherOccupation",
        "AMCST_FatherOfficeAdd" as "ALCMST_FatherOfficeAdd",
        "AMCST_FatherDesignation" as "ALCMST_FatherDesignation",
        "AMCST_FatherMonIncome" as "ALCMST_FatherMonIncome",
        "AMCST_FatherAnnIncome" as "ALCMST_FatherAnnIncome",
        "AMCST_FatherNationality" as "ALCMST_FatherNationality",
        CAST("AMCST_FatherReligion" as bigint) as "ALCMST_FatherReligion",
        CAST("AMCST_FatherCaste" as bigint) as "ALCMST_FatherCaste",
        "AMCST_FatherSubCaste" as "ALCMST_FatherSubCaste",
        "AMCST_FatherMobleNo" as "ALCMST_FatherMobleNo",
        "AMCST_FatheremailId" as "ALCMST_FatheremailId",
        "AMCST_FatherBankAccNo" as "ALCMST_FatherBankAccNo",
        "AMCST_FatherBankIFSCCode" as "ALCMST_FatherBankIFSCCode",
        "AMCST_FatherCasteCertiNo" as "ALCMST_FatherCasteCertiNo",
        "AMCST_FatherPhoto" as "ALCMST_FatherPhoto",
        "AMCST_FatherSign" as "ALCMST_FatherSign",
        "AMCST_FatherFingerprint" as "ALCMST_FatherFingerprint",
        '' as "ALCMST_FatherPANCardNo",
        "AMCST_MotherAliveFlag" as "ALCMST_MotherAliveFlag",
        "AMCST_MotherName" as "ALCMST_MotherName",
        "AMCST_MotherAadharNo" as "ALCMST_MotherAadharNo",
        "AMCST_MotherSurname" as "ALCMST_MotherSurname",
        "AMCST_MotherEducation" as "ALCMST_MotherEducation",
        "AMCST_MotherOccupation" as "ALCMST_MotherOccupation",
        "AMCST_MotherOfficeAdd" as "ALCMST_MotherOfficeAdd",
        "AMCST_MotherDesignation" as "ALCMST_MotherDesignation",
        "AMCST_MotherMonIncome" as "ALCMST_MotherMonIncome",
        "AMCST_MotherAnnIncome" as "ALCMST_MotherAnnIncome",
        "AMCST_MotherNationality" as "ALCMST_MotherNationality",
        "AMCST_MotherReligion" as "ALCMST_MotherReligion",
        "AMCST_MotherCaste" as "ALCMST_MotherCaste",
        "AMCST_MotherSubCaste" as "ALCMST_MotherSubCaste",
        "AMCST_MotherMobleNo" as "ALCMST_MotherMobleNo",
        "AMCST_MotherEmailId" as "ALCMST_MotheremailId",
        "AMCST_MotherBankAccNo" as "ALCMST_MotherBankAccNo",
        "AMCST_MotherBankIFSCCode" as "ALCMST_MotherBankIFSCCode",
        "AMCST_MotherCasteCertiNo" as "ALCMST_MotherCasteCertiNo",
        '' as "ALCMST_MotherPANCardNo",
        "AMCST_TotalIncome" as "ALCMST_TotalIncome",
        "AMCST_MotherSign" as "ALCMST_MotherSign",
        "AMCST_MotherPhoto" as "ALCMST_MotherPhoto",
        "AMCST_MotherFingerprint" as "ALCMST_MotherFingerprint",
        "AMCST_BirthPlace" as "ALCMST_BirthPlace",
        "AMCST_Nationality" as "ALCMST_Nationality",
        "AMCST_BPLCardFlag" as "ALCMST_BPLCardFlag",
        "AMCST_BPLCardNo" as "ALCMST_BPLCardNo",
        "AMCST_HostelReqdFlag" as "ALCMST_HostelReqdFlag",
        "AMCST_TransportReqdFlag" as "ALCMST_TransportReqdFlag",
        "AMCST_GymReqdFlag" as "ALCMST_GymReqdFlag",
        "AMCST_ECSFlag" as "ALCMST_ECSFlag",
        "AMCST_PaymentFlag" as "ALCMST_PaymentFlag",
        "AMCST_AmountPaid" as "ALCMST_AmountPaid",
        "AMCST_PaymentType" as "ALCMST_PaymentType",
        "AMCST_PaymentDate" as "ALCMST_PaymentDate",
        "AMCST_ReceiptNo" as "ALCMST_ReceiptNo",
        0 as "ALCMST_EMSINo",
        "AMCST_ApplStatus" as "ALCMST_ApplStatus",
        "AMCST_FinalpaymentFlag" as "ALCMST_FinalpaymentFlag",
        "AMCST_StudentPhoto" as "ALCMST_StudentPhoto",
        '' as "ALCMST_StudentSign",
        0 as "ALCMST_NoofSiblingsSchool",
        "AMCST_Noofsisters" + "AMCST_Noofsisters" as "ALCMST_NoofSiblings",
        "AMCST_Noofbrothers" as "ALCMST_NoOfBrothers",
        "AMCST_Noofsisters" as "ALCMST_NoOfSisters",
        ("AMCST_Noofsisters" + "AMCST_Noofsisters") as "ALCMST_NoofDependencies",
        "AMCST_TPINNO" as "ALCMST_TPINNO",
        1 as "IVRMMB_Id",
        '' as "ALCMST_MOInstruction",
        '' as "ALCMST_GPSTrackingId",
        '' as "ALCMST_AppDownloadedDeviceId",
        1 as "ALCMST_ActiveFlag",
        0 AS "ALCMST_CreatedBy",
        CURRENT_TIMESTAMP as "CreatedDate",
        0 AS "ALCMST_UpdatedBy",
        CURRENT_TIMESTAMP as "UpdatedDate"
    FROM "CLG"."Adm_Master_College_Student" AMCS
    INNER JOIN "CLG"."Adm_College_Yearly_Student" ASYS ON AMCS."AMCST_Id" = ASYS."AMCST_Id"
    WHERE "AMCST_SOL" = 'L' 
        AND "AMCST_ActiveFlag" = 0 
        AND ASYS."ACYST_ActiveFlag" = 0 
        AND "MI_Id" = p_MI_Id
        AND AMCS."AMCST_Id" = p_AMCST_Id 
        AND ASYS."ASMAY_Id" = p_ASMAY_Id;

    INSERT INTO "CLG"."Alumni_College_Master_Student"(
        "MI_Id","AMCST_Id","AMCO_JOIN_Id","AMB_JOIN_Id","AMSE_JOIN_Id","ASMAY_Id_Join","AMB_Id_Left","ASMAY_Id_Left",
        "AMCO_Left_Id","AMSE_Id_Left","ALCMST_FirstName",
        "ALCMST_MiddleName","ALCMST_LastName","ALCMST_Date","ALCMST_RegistrationNo",
        "ALCMST_AdmNo","ALCMST_Sex","ALCMST_DOB","ALCMST_DOBinwords",
        "ALCMST_Age","ASMCL_Id_Join","ASMCL_Id_Left","ALCMST_BloodGroup","ALCMST_MotherTongue","ALCMST_HomeLaguage",
        "ALCMST_BirthCertNo","IVRMMR_Id","IMCC_Id","IMC_Id","ALCMST_StudentSubCaste","ALCMST_PerStreet",
        "ALCMST_PerArea","ALCMST_PerCity","ALCMST_PerAdd3",
        "ALCMST_PerState","IVRMMC_Id","ALCMST_PerPincode","ALCMST_ConStreet","ALCMST_ConArea","ALCMST_ConAdd3",
        "ALCMST_ConCity","ALCMST_Village","ALCMST_Taluk","ALCMST_District",
        "ALCMST_ConState","ALCMST_ConCountryId","ALCMST_ConPincode","ALCMST_AadharNo","ALCMST_StuBankAccNo",
        "ALCMST_StudentPANCard","ALCMST_StuBankIFSCCode","ALCMST_StuCasteCertiNo","ALCMST_MobileNo",
        "ALCMST_emailId","ALCMST_FatherAliveFlag","ALCMST_FatherName","ALCMST_FatherAadharNo",
        "ALCMST_FatherSurname","ALCMST_FatherEducation","ALCMST_FatherOccupation","ALCMST_FatherOfficeAdd",
        "ALCMST_FatherDesignation","ALCMST_FatherMonIncome","ALCMST_FatherAnnIncome",
        "ALCMST_FatherNationality","ALCMST_FatherReligion","ALCMST_FatherCaste","ALCMST_FatherSubCaste",
        "ALCMST_FatherMobleNo","ALCMST_FatheremailId","ALCMST_FatherBankAccNo",
        "ALCMST_FatherBankIFSCCode","ALCMST_FatherCasteCertiNo","ALCMST_FatherPhoto","ALCMST_FatherSign",
        "ALCMST_FatherFingerprint","ALCMST_FatherPANCardNo","ALCMST_MotherAliveFlag","ALCMST_MotherName",
        "ALCMST_MotherAadharNo","ALCMST_MotherSurname","ALCMST_MotherEducation","ALCMST_MotherOccupation",
        "ALCMST_MotherOfficeAdd","ALCMST_MotherDesignation","ALCMST_MotherMonIncome","ALCMST_MotherAnnIncome",
        "ALCMST_MotherNationality","ALCMST_MotherReligion","ALCMST_MotherCaste","ALCMST_MotherSubCaste",
        "ALCMST_MotherMobleNo","ALCMST_MotheremailId","ALCMST_MotherBankAccNo","ALCMST_MotherBankIFSCCode",
        "ALCMST_MotherCasteCertiNo","ALCMST_MotherPANCardNo",
        "ALCMST_TotalIncome","ALCMST_MotherSign","ALCMST_MotherPhoto","ALCMST_MotherFingerprint",
        "ALCMST_BirthPlace","ALCMST_Nationality","ALCMST_BPLCardFlag","ALCMST_BPLCardNo",
        "ALCMST_HostelReqdFlag","ALCMST_TransportReqdFlag","ALCMST_GymReqdFlag",
        "ALCMST_ECSFlag","ALCMST_PaymentFlag","ALCMST_AmountPaid","ALCMST_PaymentType","ALCMST_PaymentDate",
        "ALCMST_ReceiptNo","ALCMST_EMSINo","ALCMST_ApplStatus","ALCMST_FinalpaymentFlag",
        "ALCMST_StudentPhoto","ALCMST_StudentSign","ALCMST_StudentFingerprint","ALCMST_NoofSiblingsSchool",
        "ALCMST_NoofSiblings","ALCMST_NoOfBrothers","ALCMST_NoOfSisters","ALCMST_NoofDependencies",
        "ALCMST_TPINNO","IVRMMB_Id","ALCMST_MOInstruction","ALCMST_GPSTrackingId","ALCMST_AppDownloadedDeviceId",
        "ALCMST_ActiveFlag","ALCMST_CreatedBy","CreatedDate","ALCMST_UpdatedBy","UpdatedDate")
    SELECT 
        A."MI_Id","AMCST_Id","AMCO_JOIN_Id","AMB_JOIN_Id","AMSE_JOIN_Id","ASMAY_Id_Join","AMB_Id_Left","ASMAY_Id_Left",
        "AMCO_Left_Id","AMSE_Id_Left","ALCMST_FirstName",
        "ALCMST_MiddleName","ALCMST_LastName","ALCMST_Date","ALCMST_RegistrationNo",
        "ALCMST_AdmNo","ALCMST_Sex","ALCMST_DOB","ALCMST_DOBinwords",
        "ALCMST_Age","ASMCL_Id_Join","ASMCL_Id_Left","ALCMST_BloodGroup","ALCMST_MotherTongue","ALCMST_HomeLaguage",
        "ALCMST_BirthCertNo","IVRMMR_Id","IMCC_Id","IMC_Id","ALCMST_StudentSubCaste","ALCMST_PerStreet",
        "ALCMST_PerArea","ALCMST_PerCity","ALCMST_PerAdd3",
        "ALCMST_PerState","IVRMMC_Id","ALCMST_PerPincode","ALCMST_ConStreet","ALCMST_ConArea","ALCMST_ConAdd3",
        "ALCMST_ConCity","ALCMST_Village","ALCMST_Taluk","ALCMST_District",
        "ALCMST_ConState","ALCMST_ConCountryId","ALCMST_ConPincode","ALCMST_AadharNo","ALCMST_StuBankAccNo",
        "ALCMST_StudentPANCard","ALCMST_StuBankIFSCCode","ALCMST_StuCasteCertiNo","ALCMST_MobileNo",
        "ALCMST_emailId","ALCMST_FatherAliveFlag","ALCMST_FatherName","ALCMST_FatherAadharNo",
        "ALCMST_FatherSurname","ALCMST_FatherEducation","ALCMST_FatherOccupation","ALCMST_FatherOfficeAdd",
        "ALCMST_FatherDesignation","ALCMST_FatherMonIncome","ALCMST_FatherAnnIncome",
        "ALCMST_FatherNationality","ALCMST_FatherReligion","ALCMST_FatherCaste","ALCMST_FatherSubCaste",
        "ALCMST_FatherMobleNo","ALCMST_FatheremailId","ALCMST_FatherBankAccNo",
        "ALCMST_FatherBankIFSCCode","ALCMST_FatherCasteCertiNo","ALCMST_FatherPhoto","ALCMST_FatherSign",
        "ALCMST_FatherFingerprint","ALCMST_FatherPANCardNo","ALCMST_MotherAliveFlag","ALCMST_MotherName",
        "ALCMST_MotherAadharNo","ALCMST_MotherSurname","ALCMST_MotherEducation","ALCMST_MotherOccupation",
        "ALCMST_MotherOfficeAdd","ALCMST_MotherDesignation","ALCMST_MotherMonIncome","ALCMST_MotherAnnIncome",
        "ALCMST_MotherNationality","ALCMST_MotherReligion","ALCMST_MotherCaste","ALCMST_MotherSubCaste",
        "ALCMST_MotherMobleNo","ALCMST_MotheremailId","ALCMST_MotherBankAccNo","ALCMST_MotherBankIFSCCode",
        "ALCMST_MotherCasteCertiNo","ALCMST_MotherPANCardNo",
        "ALCMST_TotalIncome","ALCMST_MotherSign","ALCMST_MotherPhoto","ALCMST_MotherFingerprint",
        "ALCMST_BirthPlace","ALCMST_Nationality","ALCMST_BPLCardFlag","ALCMST_BPLCardNo",
        "ALCMST_HostelReqdFlag","ALCMST_TransportReqdFlag","ALCMST_GymReqdFlag",
        "ALCMST_ECSFlag","ALCMST_PaymentFlag","ALCMST_AmountPaid","ALCMST_PaymentType","ALCMST_PaymentDate",
        "ALCMST_ReceiptNo","ALCMST_EMSINo","ALCMST_ApplStatus","ALCMST_FinalpaymentFlag",
        "ALCMST_StudentPhoto","ALCMST_StudentSign",0 as "ALCMST_StudentFingerprint","ALCMST_NoofSiblingsSchool",
        "ALCMST_NoofSiblings","ALCMST_NoOfBrothers","ALCMST_NoOfSisters","ALCMST_NoofDependencies",
        "ALCMST_TPINNO",B."IVRMMB_Id","ALCMST_MOInstruction","ALCMST_GPSTrackingId","ALCMST_AppDownloadedDeviceId",
        "ALCMST_ActiveFlag","ALCMST_CreatedBy",A."CreatedDate","ALCMST_UpdatedBy",A."UpdatedDate"
    FROM "ALU_M_clg_student_Temp" A 
    LEFT JOIN "IVRM_Master_Board" B ON A."MI_Id" = B."MI_Id";

    RETURN;
END;
$$;