CREATE OR REPLACE FUNCTION "ISM_REOPEN_TASK_DETAILS"(
    p_HRME_ID BIGINT,
    p_FROMDATE VARCHAR(100),
    p_year_id VARCHAR(100)
)
RETURNS BIGINT
LANGUAGE plpgsql
AS $$
DECLARE
    v_COUNT BIGINT;
    v_MI_ID BIGINT;
    v_MONTH_ID BIGINT;
    v_CURRENTDATE DATE;
BEGIN
    v_CURRENTDATE := CURRENT_DATE;

    SELECT "MI_ID" INTO v_MI_ID 
    FROM "HR_Master_Employee" 
    WHERE "HRME_Id" = p_HRME_ID;

    SELECT COUNT(b."ISMTCR_Id") INTO v_COUNT
    FROM "ISM_TaskCreation_Response" a 
    INNER JOIN "ISM_TaskCreation" b ON a."ISMTCR_Id" = b."ISMTCR_Id"
    WHERE a."HRME_Id" = p_HRME_ID 
    AND EXTRACT(MONTH FROM a."ISMTCRRES_ResponseDate") = v_MONTH_ID 
    AND EXTRACT(YEAR FROM a."ISMTCRRES_ResponseDate") = p_year_id::INTEGER
    AND CAST(b."ISMTCR_ReOpenDate" AS DATE) BETWEEN p_FROMDATE::DATE AND v_CURRENTDATE
    AND b."ISMTCR_ReOpenFlg" = 1;

    RETURN v_COUNT;
END;
$$;