CREATE OR REPLACE FUNCTION "dbo"."ISM_DailyReport_TaskDetails" (
    "MI_Id" TEXT,
    "ISMTCR_Id" TEXT,
    "FLAG" TEXT
)
RETURNS SETOF REFCURSOR
LANGUAGE plpgsql
AS $$
DECLARE
    "Slqdymaic" TEXT;
    result_cursor REFCURSOR := 'result_cursor';
BEGIN

    IF "FLAG" = '1' THEN
    
        "Slqdymaic" := '
        SELECT DISTINCT A."ISMTCR_ID", A."HRMD_ID", A."HRMPR_ID", E."HRMP_NAME", A."ISMTCR_BUGORENHANCEMENTFLG", 
        A."ISMTCR_CREATIONDATE", A."ISMTCR_TITLE", A."ISMTCR_DESC",
        (CASE WHEN TAT."ISMTCRASTO_STARTDATE" IS NULL THEN CURRENT_TIMESTAMP ELSE TAT."ISMTCRASTO_STARTDATE" END) AS "ISMTCRASTO_STARTDATE",
        (CASE WHEN TAT."ISMTCRASTO_ENDDATE" IS NULL THEN CURRENT_TIMESTAMP ELSE TAT."ISMTCRASTO_ENDDATE" END) AS "ISMTCRASTO_ENDDATE",
        A."ISMTCR_STATUS", A."ISMTCR_REOPENFLG", A."ISMTCR_REOPENDATE", A."ISMTCR_TASKNO", AC."ISMMCLT_ID", 
        CL."ISMMCLT_CLIENTNAME", TCR."ISMTCRRES_ID", TATT."ISMTCRAT_ATTATCHMENT",
        (CASE WHEN A."ISMTCR_BUGORENHANCEMENTFLG" = ''B'' THEN ''BUG/COMPLAINTS''
        WHEN A."ISMTCR_BUGORENHANCEMENTFLG" = ''E'' THEN ''ENHANCEMENT'' ELSE ''OTHERS'' END) AS "TASKTYPE"
        
        FROM "ISM_TASKCREATION" A
        LEFT JOIN "ISM_TASKCREATION_CLIENT" AC ON A."ISMTCR_ID" = AC."ISMTCR_ID"
        LEFT JOIN "ISM_TASKCREATION_ASSIGNEDTO" TAT ON TAT."ISMTCR_ID" = A."ISMTCR_ID"
        LEFT JOIN "ISM_MASTER_CLIENT" CL ON AC."ISMMCLT_ID" = CL."ISMMCLT_ID" AND CL."ISMMCLT_ACTIVEFLAG" = 1
        LEFT JOIN "ISM_TASKCREATION_RESPONSE" TCR ON TCR."ISMTCR_ID" = A."ISMTCR_ID" AND TCR."ISMTCRRES_ACTIVEFLG" = 1
        LEFT JOIN "ISM_TASKCREATION_ATTACHMENT" TATT ON TATT."ISMTCR_ID" = A."ISMTCR_ID" AND TATT."ISMTCRAT_ACTIVEFLG" = 1
        INNER JOIN "HR_MASTER_PRIORITY" E ON A."HRMPR_ID" = E."HRMPR_ID" AND E."HRMP_ACTIVEFLAG" = 1
        WHERE A."ISMTCR_ACTIVEFLG" = 1 AND A."ISMTCR_ID" = ' || "ISMTCR_Id" || '
        ORDER BY "ISMTCRRES_ID" DESC';
        
        OPEN result_cursor FOR EXECUTE "Slqdymaic";
        RETURN NEXT result_cursor;
        
    ELSIF "FLAG" = '2' THEN
    
        "Slqdymaic" := '
        SELECT DISTINCT A."ISMTCR_ID", A."HRMPR_ID", E."HRMP_NAME", A."ISMTCR_BUGORENHANCEMENTFLG", 
        A."ISMTCR_CREATIONDATE", A."ISMTCR_TITLE", A."ISMTCR_DESC",
        A."ISMTCR_STATUS", A."ISMTCR_REOPENFLG", A."ISMTCR_REOPENDATE", A."ISMTCR_TASKNO", AC."ISMMCLT_ID", 
        CL."ISMMCLT_CLIENTNAME", TCR."ISMTCRRES_RESPONSEDATE",
        (CASE WHEN A."ISMTCR_BUGORENHANCEMENTFLG" = ''B'' THEN ''BUG/COMPLAINTS''
        WHEN A."ISMTCR_BUGORENHANCEMENTFLG" = ''E'' THEN ''ENHANCEMENT''
        ELSE ''OTHERS'' END) AS "TASKTYPE", TCR."ISMTCRRES_RESPONSE",
        ((CASE WHEN C."HRME_EMPLOYEEFIRSTNAME" IS NULL OR C."HRME_EMPLOYEEFIRSTNAME" = '''' THEN ''''
        ELSE C."HRME_EMPLOYEEFIRSTNAME" END || 
        CASE WHEN C."HRME_EMPLOYEEMIDDLENAME" IS NULL OR C."HRME_EMPLOYEEMIDDLENAME" = '''' 
        OR C."HRME_EMPLOYEEMIDDLENAME" = ''0'' THEN '''' ELSE '' '' || C."HRME_EMPLOYEEMIDDLENAME" END || 
        CASE WHEN C."HRME_EMPLOYEELASTNAME" IS NULL OR C."HRME_EMPLOYEELASTNAME" = ''''
        OR C."HRME_EMPLOYEELASTNAME" = ''0'' THEN '''' ELSE '' '' || C."HRME_EMPLOYEELASTNAME" END)) AS "RESPONSEBY",
        TCR."CREATEDDATE", TCR."ISMTCRRES_STATUS"
        
        FROM "ISM_TASKCREATION" A
        LEFT JOIN "ISM_TASKCREATION_CLIENT" AC ON A."ISMTCR_ID" = AC."ISMTCR_ID"
        LEFT JOIN "ISM_MASTER_CLIENT" CL ON AC."ISMMCLT_ID" = CL."ISMMCLT_ID" AND CL."ISMMCLT_ACTIVEFLAG" = 1
        LEFT JOIN "ISM_TASKCREATION_RESPONSE" TCR ON TCR."ISMTCR_ID" = A."ISMTCR_ID" AND TCR."ISMTCRRES_ACTIVEFLG" = 1
        LEFT JOIN "HR_MASTER_EMPLOYEE" C ON TCR."HRME_ID" = C."HRME_ID" AND C."HRME_ACTIVEFLAG" = 1 AND C."HRME_LEFTFLAG" = 0
        INNER JOIN "HR_MASTER_PRIORITY" E ON A."HRMPR_ID" = E."HRMPR_ID" AND E."HRMP_ACTIVEFLAG" = 1
        
        WHERE A."ISMTCR_ACTIVEFLG" = 1 AND A."ISMTCR_ID" = ' || "ISMTCR_Id" || '
        ORDER BY TCR."CREATEDDATE" DESC';
        
        OPEN result_cursor FOR EXECUTE "Slqdymaic";
        RETURN NEXT result_cursor;
        
    ELSIF "FLAG" = '3' THEN
    
        OPEN result_cursor FOR
        SELECT "ISMTCRAT_ATTATCHMENT", "ISMTCR_ID", "ISMTCRAT_ID" 
        FROM "ISM_TASKCREATION_ATTACHMENT" 
        WHERE "ISMTCR_ID" = "ISMTCR_Id"::BIGINT;
        RETURN NEXT result_cursor;
        
    ELSIF "FLAG" = '4' THEN
    
        OPEN result_cursor FOR
        SELECT "ISMTCRRES_RESPONSE", "ISMTCRRES_RESPONSEATTACHMENT", "ISMTCR_ID", "ISMTCRRES_ID", "ISMTCRRES_STATUS" 
        FROM "ISM_TASKCREATION_RESPONSE" 
        WHERE "ISMTCR_ID" = "ISMTCR_Id"::BIGINT;
        RETURN NEXT result_cursor;
        
    END IF;

END;
$$;