CREATE OR REPLACE FUNCTION "dbo"."Institutedetails_AdminData"(
    p_MI_Id bigint
)
RETURNS TABLE(
    "MI_Id" bigint,
    "MO_Id" bigint,
    "MI_Name" varchar,
    "MI_Type" varchar,
    "MI_Address1" varchar,
    "MI_Address2" varchar,
    "MI_Address3" varchar,
    "MI_AddressArea" varchar,
    "IVRMMCT_Name" varchar,
    "IVRMMS_Id" bigint,
    "IVRMMC_Id" bigint,
    "MI_Pincode" varchar,
    "MI_FaxNo" varchar,
    "MI_BackgroundImage" varchar,
    "MI_FormColor" varchar,
    "MI_FontColor" varchar,
    "MI_FontSize" varchar,
    "MI_WeekStartDay" varchar,
    "MI_DateFormat" varchar,
    "MI_DateSeparator" varchar,
    "MI_Logo" varchar,
    "MI_Precision" integer,
    "MI_GradingSystem" varchar,
    "MI_PasswordFlag" boolean,
    "MI_ActiveFlag" boolean,
    "MI_Affiliation" varchar,
    "CreatedDate" timestamp,
    "UpdatedDate" timestamp,
    "MI_Subdomain" varchar,
    "MI_FranchiseFlag" boolean,
    "MI_AboutInstitute" text,
    "MI_ContactDetails" varchar,
    "MI_HelpFile" varchar,
    "MI_SchoolCollegeFlag" varchar,
    "MI_PAN" varchar,
    "MI_TAN" varchar,
    "MI_GPSUserName" varchar,
    "MI_IVRSVirtualNo" varchar,
    "MI_IVRSOutboundNo" varchar,
    "MI_NAAC_InstitutionTypeFlg" varchar,
    "MI_PGDisplayName" varchar,
    "MI_PGDisplayLogo" varchar,
    "MI_NAAC_SubInstitutionTypeFlg" varchar,
    "MI_PaymentReminderAPI" varchar,
    "MI_VCStudentFlag" boolean,
    "MI_VCOthersFlag" boolean,
    "MI_Code" varchar,
    "MI_MSTeamsClientId" varchar,
    "MI_MSTeamsTenentId" varchar,
    "MI_MSTemasClinetSecretCode" varchar,
    "MI_MSTeamsAppAccessTockenURL" varchar,
    "MI_MSTeamsUserAceessTockenURL" varchar,
    "MI_MSTeamsMeetingScheduleURL" varchar,
    "MI_MSTeamsAdminUsername" varchar,
    "MI_MSTeamsAdminPassword" varchar,
    "MI_MSTeamsScope" varchar,
    "MI_MSTeamsGrantType" varchar,
    "MI_80GRegNo" varchar,
    "MI_SMSCountAlert" varchar,
    "MI_SMSAlertToemailids" varchar,
    "MI_GSTNO" varchar,
    "MI_CINNo" varchar,
    "MI_WhatsAppAudioUrl" varchar,
    "MI_WhatsAppImageUrl" varchar,
    "MI_WhatsAppPdfUrl" varchar,
    "MI_WhatsAppTextUrl" varchar,
    "MI_WhatsAppVideoUrl" varchar,
    "MI_EntityId" varchar,
    "MI_CreatedBy" bigint,
    "MI_UpdatedBy" bigint,
    "MI_FilePath" varchar,
    "MI_PGRegisteredEmailId" varchar,
    "MIE_EmailId" varchar,
    "MIMN_MobileNo" varchar,
    "MIPN_PhoneNo" varchar,
    "IVRMGC_Webiste" varchar
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        mi."MI_Id",
        mi."MO_Id",
        mi."MI_Name",
        mi."MI_Type",
        mi."MI_Address1",
        mi."MI_Address2",
        mi."MI_Address3",
        mi."MI_AddressArea",
        mi."IVRMMCT_Name",
        mi."IVRMMS_Id",
        mi."IVRMMC_Id",
        mi."MI_Pincode",
        mi."MI_FaxNo",
        mi."MI_BackgroundImage",
        mi."MI_FormColor",
        mi."MI_FontColor",
        mi."MI_FontSize",
        mi."MI_WeekStartDay",
        mi."MI_DateFormat",
        mi."MI_DateSeparator",
        mi."MI_Logo",
        mi."MI_Precision",
        mi."MI_GradingSystem",
        mi."MI_PasswordFlag",
        mi."MI_ActiveFlag",
        mi."MI_Affiliation",
        mi."CreatedDate",
        mi."UpdatedDate",
        mi."MI_Subdomain",
        mi."MI_FranchiseFlag",
        mi."MI_AboutInstitute",
        mi."MI_ContactDetails",
        mi."MI_HelpFile",
        mi."MI_SchoolCollegeFlag",
        mi."MI_PAN",
        mi."MI_TAN",
        mi."MI_GPSUserName",
        mi."MI_IVRSVirtualNo",
        mi."MI_IVRSOutboundNo",
        mi."MI_NAAC_InstitutionTypeFlg",
        mi."MI_PGDisplayName",
        mi."MI_PGDisplayLogo",
        mi."MI_NAAC_SubInstitutionTypeFlg",
        mi."MI_PaymentReminderAPI",
        mi."MI_VCStudentFlag",
        mi."MI_VCOthersFlag",
        mi."MI_Code",
        mi."MI_MSTeamsClientId",
        mi."MI_MSTeamsTenentId",
        mi."MI_MSTemasClinetSecretCode",
        mi."MI_MSTeamsAppAccessTockenURL",
        mi."MI_MSTeamsUserAceessTockenURL",
        mi."MI_MSTeamsMeetingScheduleURL",
        mi."MI_MSTeamsAdminUsername",
        mi."MI_MSTeamsAdminPassword",
        mi."MI_MSTeamsScope",
        mi."MI_MSTeamsGrantType",
        mi."MI_80GRegNo",
        mi."MI_SMSCountAlert",
        mi."MI_SMSAlertToemailids",
        mi."MI_GSTNO",
        mi."MI_CINNo",
        mi."MI_WhatsAppAudioUrl",
        mi."MI_WhatsAppImageUrl",
        mi."MI_WhatsAppPdfUrl",
        mi."MI_WhatsAppTextUrl",
        mi."MI_WhatsAppVideoUrl",
        mi."MI_EntityId",
        mi."MI_CreatedBy",
        mi."MI_UpdatedBy",
        mi."MI_FilePath",
        mi."MI_PGRegisteredEmailId",
        (SELECT "MIE_EmailId" FROM "Master_Institution_EmailId" WHERE "MI_Id" = p_MI_Id LIMIT 1)::varchar AS "MIE_EmailId",
        (SELECT "MIMN_MobileNo" FROM "Master_Institution_MobileNo" WHERE "MI_Id" = p_MI_Id LIMIT 1)::varchar AS "MIMN_MobileNo",
        (SELECT "MIPN_PhoneNo" FROM "Master_Institution_Phone_No" WHERE "MI_Id" = p_MI_Id LIMIT 1)::varchar AS "MIPN_PhoneNo",
        (SELECT "IVRMGC_Webiste" FROM "IVRM_General_Cofiguration_New" WHERE "MI_Id" = p_MI_Id LIMIT 1)::varchar AS "IVRMGC_Webiste"
    FROM "dbo"."Master_Institution" mi
    WHERE mi."MI_Id" = p_MI_Id;
    
    RETURN;
END;
$$;