CREATE OR REPLACE FUNCTION "IVRM_MOBILEAPP_SCHOOLCODE_NEWSHAREDHOST_COLLEGE"(
    "MI_Id" BIGINT,
    "SCHOOLNAME" VARCHAR(500),
    "SCHOOLLOGO" TEXT,
    "SCHOOLCODE" VARCHAR(500)
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    "IIVRSC_IdNEW" BIGINT;
BEGIN

    INSERT INTO "IVRM_IVRS_Configuration" ("IIVRSC_MI_Id", "IIVRSC_VirtualNo", "IIVRSC_SchoolName", "IIVRSC_URL", "IIVRSC_VFORTTSFlg", "IIVRSC_ActiveFlg", "CreatedDate", "UpdatedDate", "IIVRSC_SchoolFlg", "IIVRSC_AppLogo", "IIVRSC_SchoolCode")
    SELECT "MI_Id", "IIVRSC_VirtualNo", "SCHOOLNAME", "IIVRSC_URL", "IIVRSC_VFORTTSFlg", 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1, "SCHOOLLOGO", "SCHOOLCODE"
    FROM "IVRM_IVRS_Configuration" 
    WHERE "IIVRSC_Id" = 158
    RETURNING "IIVRSC_Id" INTO "IIVRSC_IdNEW";

    INSERT INTO "IVRM_Configuration_URL" ("IIVRSC_Id", "IIVRSCURL_APIName", "IIVRSCURL_APIURL", "IIVRSCURL_CreatedDate", "IIVRSCURL_UpdatedDate", "IIVRSCURL_CreatedBy", "IIVRSCURL_UpdatedBy")
    SELECT "IIVRSC_IdNEW", "IIVRSCURL_APIName", "IIVRSCURL_APIURL", CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', ''
    FROM "IVRM_Configuration_URL" 
    WHERE "IIVRSC_Id" = 158;

END;
$$;