CREATE OR REPLACE FUNCTION "dbo"."fee_report_details_1_test"(
    "asmay_id" VARCHAR(10),
    "asmcl_id" VARCHAR(10),
    "asms_id" VARCHAR(10),
    "fmh_id" VARCHAR(10),
    "fmt_ids" TEXT,
    "type" VARCHAR(10),
    "trmr_id" VARCHAR(10),
    "mi_id" VARCHAR(10),
    "userid" VARCHAR(10),
    "active" VARCHAR(50),
    "deactive" VARCHAR(50),
    "left" VARCHAR(50),
    "report" VARCHAR(50),
    "details" VARCHAR(50)
)
RETURNS SETOF RECORD
LANGUAGE plpgsql
AS $$
DECLARE
    "query" TEXT;
    "amst_sol" TEXT;
    "sql1" TEXT;
    "sql2" TEXT;
BEGIN
    IF "fmh_id" = '0' THEN
        "sql1" := ' ';
    ELSE
        "sql1" := 'and "dbo"."Fee_Master_Head"."fmh_id"=' || "fmh_id" || '';
    END IF;

    IF "asmcl_id" = '0' THEN
        "sql2" := ' ';
    ELSE
        IF "asms_id" = '0' THEN
            "sql2" := 'AND ("dbo"."Adm_School_Y_Student"."ASMCL_Id" = ' || "asmcl_id" || ')';
        ELSE
            "sql2" := 'AND ("dbo"."Adm_School_Y_Student"."ASMCL_Id" = ' || "asmcl_id" || ')AND ("dbo"."Adm_School_Y_Student"."ASMS_Id" = ' || "asms_id" || ') ';
        END IF;
    END IF;

    IF "active" = '1' AND "deactive" = '0' AND "left" = '0' THEN
        "amst_sol" := 'and ("Adm_School_Y_Student"."AMAY_ActiveFlag"=1)and ("Adm_M_Student"."AMST_SOL"=''S'') and ("Adm_M_Student"."AMST_ActiveFlag"=1)';
    ELSIF "deactive" = '1' AND "active" = '0' AND "left" = '0' THEN
        "amst_sol" := 'and ("Adm_School_Y_Student"."AMAY_ActiveFlag"=1)and ("Adm_M_Student"."AMST_SOL"=''D'') and ("Adm_M_Student"."AMST_ActiveFlag"=1)';
    ELSIF "left" = '1' AND "active" = '0' AND "deactive" = '0' THEN
        "amst_sol" := 'and ("Adm_School_Y_Student"."AMAY_ActiveFlag"=0)and ("Adm_M_Student"."AMST_SOL"=''L'') and ("Adm_M_Student"."AMST_ActiveFlag"=0)';
    ELSIF "left" = '1' AND "active" = '1' AND "deactive" = '0' THEN
        "amst_sol" := 'and ("Adm_School_Y_Student"."AMAY_ActiveFlag" in (0,1))and ("Adm_M_Student"."AMST_SOL" in (''L'',''S'')) and ("Adm_M_Student"."AMST_ActiveFlag" in(0,1))';
    ELSIF "left" = '1' AND "active" = '0' AND "deactive" = '1' THEN
        "amst_sol" := 'and ("Adm_School_Y_Student"."AMAY_ActiveFlag" in (0,1))and ("Adm_M_Student"."AMST_SOL" in (''L'',''D'')) and ("Adm_M_Student"."AMST_ActiveFlag" in(0,1))';
    ELSIF "left" = '0' AND "active" = '1' AND "deactive" = '1' THEN
        "amst_sol" := 'and ("Adm_School_Y_Student"."AMAY_ActiveFlag" in (1))and ("Adm_M_Student"."AMST_SOL" in (''S'',''D'')) and ("Adm_M_Student"."AMST_ActiveFlag" in(1))';
    ELSE
        "amst_sol" := ' ';
    END IF;

    IF "report" = 'all' THEN
        IF "trmr_id" = '0' THEN
            IF "type" = 'FSW' THEN
                "query" := 'SELECT  distinct      (COALESCE("dbo"."Adm_M_Student"."AMST_FirstName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_MiddleName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_LastName",'''')) "StudentName", "dbo"."Adm_School_M_Class"."ASMCL_ClassName" || '':'' || "dbo"."Adm_School_M_Section"."ASMC_SectionName" as "ASMCL_ClassName", sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount") as "FSS_OBArrearAmount", sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") as "FSS_OBExcessAmount", sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") as "FSS_WaivedAmount", sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount") as "FSS_AdjustedAmount", sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") as "FSS_RefundAmount" FROM "dbo"."Fee_Yearly_Group_Head_Mapping" INNER JOIN "dbo"."Fee_Master_Head" ON "dbo"."Fee_Yearly_Group_Head_Mapping"."FMH_Id" = "dbo"."Fee_Master_Head"."FMH_Id" INNER JOIN "dbo"."Fee_Master_Terms_FeeHeads" ON "dbo"."Fee_Master_Head"."FMH_Id" = "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" INNER JOIN "dbo"."Fee_Student_Status" INNER JOIN "dbo"."Adm_M_Student" ON "dbo"."Fee_Student_Status"."AMST_Id" = "dbo"."Adm_M_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_Y_Student" ON "dbo"."Adm_M_Student"."AMST_Id" = "dbo"."Adm_School_Y_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_M_Class" ON "dbo"."Adm_School_Y_Student"."ASMCL_Id" = "dbo"."Adm_School_M_Class"."ASMCL_Id" INNER JOIN "dbo"."Adm_School_M_Section" ON "dbo"."Adm_School_Y_Student"."ASMS_Id" = "dbo"."Adm_School_M_Section"."ASMS_Id" ON "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" = "dbo"."Fee_Student_Status"."FMH_Id" AND "dbo"."Fee_Master_Terms_FeeHeads"."FTI_Id" = "dbo"."Fee_Student_Status"."FTI_Id" WHERE ("dbo"."Adm_School_Y_Student"."ASMAY_Id" = ' || "asmay_id" || ') and ("dbo"."Fee_Student_Status"."MI_Id"=' || "mi_id" || ') ' || "sql2" || ' ' || "sql1" || ' AND ("dbo"."Fee_Master_Terms_FeeHeads"."FMT_Id" IN (' || "fmt_ids" || ')) ' || "amst_sol" || ' group by "ASMCL_ClassName","ASMC_SectionName","AMST_FirstName","AMST_MiddleName","AMST_LastName" having sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") >0';
            ELSIF "type" = 'FRW' THEN
                "query" := 'SELECT  distinct  "TRMR_RouteName", sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount") as "FSS_OBArrearAmount", sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") as "FSS_OBExcessAmount", sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") as "FSS_WaivedAmount", sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount") as "FSS_AdjustedAmount", sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") as "FSS_RefundAmount" FROM "dbo"."Fee_Yearly_Group_Head_Mapping" INNER JOIN "dbo"."Fee_Master_Head" ON "dbo"."Fee_Yearly_Group_Head_Mapping"."FMH_Id" = "dbo"."Fee_Master_Head"."FMH_Id" INNER JOIN "dbo"."Fee_Master_Terms_FeeHeads" ON "dbo"."Fee_Master_Head"."FMH_Id" = "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" INNER JOIN "dbo"."Fee_Student_Status" INNER JOIN "dbo"."Adm_M_Student" ON "dbo"."Fee_Student_Status"."AMST_Id" = "dbo"."Adm_M_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_Y_Student" ON "dbo"."Adm_M_Student"."AMST_Id" = "dbo"."Adm_School_Y_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_M_Class" ON "dbo"."Adm_School_Y_Student"."ASMCL_Id" = "dbo"."Adm_School_M_Class"."ASMCL_Id" INNER JOIN "dbo"."Adm_School_M_Section" ON "dbo"."Adm_School_Y_Student"."ASMS_Id" = "dbo"."Adm_School_M_Section"."ASMS_Id" ON "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" = "dbo"."Fee_Student_Status"."FMH_Id" AND "dbo"."Fee_Master_Terms_FeeHeads"."FTI_Id" = "dbo"."Fee_Student_Status"."FTI_Id" inner join "trn"."TR_Student_Route" on  "trn"."TR_Student_Route"."AMST_Id"="dbo"."Fee_Student_Status"."AMST_Id" inner join "trn"."TR_Master_Route" on "trn"."TR_Master_Route"."TRMR_Id"="trn"."TR_Student_Route"."TRMR_Id" WHERE ("dbo"."Adm_School_Y_Student"."ASMAY_Id" = ' || "asmay_id" || ') and ("dbo"."Fee_Student_Status"."MI_Id"=' || "mi_id" || ') ' || "sql2" || '   ' || "sql1" || ' AND ("dbo"."Fee_Master_Terms_FeeHeads"."FMT_Id" IN (' || "fmt_ids" || ')) ' || "amst_sol" || ' group by "TRMR_RouteName" having sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") >0';
            ELSIF "type" = 'FHW' THEN
                "query" := 'SELECT  distinct "dbo"."Fee_Master_Head"."FMH_FeeName", sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount") as "FSS_OBArrearAmount", sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") as "FSS_OBExcessAmount", sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") as "FSS_WaivedAmount", sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount") as "FSS_AdjustedAmount", sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") as "FSS_RefundAmount" FROM "dbo"."Fee_Yearly_Group_Head_Mapping" INNER JOIN "dbo"."Fee_Master_Head" ON "dbo"."Fee_Yearly_Group_Head_Mapping"."FMH_Id" = "dbo"."Fee_Master_Head"."FMH_Id" INNER JOIN "dbo"."Fee_Master_Terms_FeeHeads" ON "dbo"."Fee_Master_Head"."FMH_Id" = "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" INNER JOIN "dbo"."Fee_Student_Status" INNER JOIN "dbo"."Adm_M_Student" ON "dbo"."Fee_Student_Status"."AMST_Id" = "dbo"."Adm_M_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_Y_Student" ON "dbo"."Adm_M_Student"."AMST_Id" = "dbo"."Adm_School_Y_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_M_Class" ON "dbo"."Adm_School_Y_Student"."ASMCL_Id" = "dbo"."Adm_School_M_Class"."ASMCL_Id" INNER JOIN "dbo"."Adm_School_M_Section" ON "dbo"."Adm_School_Y_Student"."ASMS_Id" = "dbo"."Adm_School_M_Section"."ASMS_Id" ON "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" = "dbo"."Fee_Student_Status"."FMH_Id" AND "dbo"."Fee_Master_Terms_FeeHeads"."FTI_Id" = "dbo"."Fee_Student_Status"."FTI_Id" WHERE ("dbo"."Adm_School_Y_Student"."ASMAY_Id" = ' || "asmay_id" || ') and ("dbo"."Fee_Student_Status"."MI_Id"=' || "mi_id" || ') ' || "sql2" || '   ' || "sql1" || ' AND ("dbo"."Fee_Master_Terms_FeeHeads"."FMT_Id" IN (' || "fmt_ids" || ')) ' || "amst_sol" || ' group by "dbo"."Fee_Master_Head"."FMH_FeeName" having sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") >0';
            ELSE
                "query" := 'SELECT  distinct "dbo"."Adm_School_M_Class"."ASMCL_ClassName" || '':'' || "dbo"."Adm_School_M_Section"."ASMC_SectionName" as "ASMCL_ClassName", sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount") as "FSS_OBArrearAmount", sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") as "FSS_OBExcessAmount", sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") as "FSS_WaivedAmount", sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount") as "FSS_AdjustedAmount", sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") as "FSS_RefundAmount" FROM "dbo"."Fee_Yearly_Group_Head_Mapping" INNER JOIN "dbo"."Fee_Master_Head" ON "dbo"."Fee_Yearly_Group_Head_Mapping"."FMH_Id" = "dbo"."Fee_Master_Head"."FMH_Id" INNER JOIN "dbo"."Fee_Master_Terms_FeeHeads" ON "dbo"."Fee_Master_Head"."FMH_Id" = "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" INNER JOIN "dbo"."Fee_Student_Status" INNER JOIN "dbo"."Adm_M_Student" ON "dbo"."Fee_Student_Status"."AMST_Id" = "dbo"."Adm_M_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_Y_Student" ON "dbo"."Adm_M_Student"."AMST_Id" = "dbo"."Adm_School_Y_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_M_Class" ON "dbo"."Adm_School_Y_Student"."ASMCL_Id" = "dbo"."Adm_School_M_Class"."ASMCL_Id" INNER JOIN "dbo"."Adm_School_M_Section" ON "dbo"."Adm_School_Y_Student"."ASMS_Id" = "dbo"."Adm_School_M_Section"."ASMS_Id" ON "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" = "dbo"."Fee_Student_Status"."FMH_Id" AND "dbo"."Fee_Master_Terms_FeeHeads"."FTI_Id" = "dbo"."Fee_Student_Status"."FTI_Id" WHERE ("dbo"."Adm_School_Y_Student"."ASMAY_Id" = ' || "asmay_id" || ') and ("dbo"."Fee_Student_Status"."MI_Id"=' || "mi_id" || ') ' || "sql2" || '  ' || "sql1" || ' AND ("dbo"."Fee_Master_Terms_FeeHeads"."FMT_Id" IN (' || "fmt_ids" || ')) ' || "amst_sol" || ' group by "ASMCL_ClassName","ASMC_SectionName" having sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") >0';
            END IF;
        ELSE
            "query" := 'SELECT  distinct      (COALESCE("dbo"."Adm_M_Student"."AMST_FirstName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_MiddleName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_LastName",'''')) "StudentName", "dbo"."Adm_School_M_Class"."ASMCL_ClassName" || '':'' || "dbo"."Adm_School_M_Section"."ASMC_SectionName" as "ASMCL_ClassName", sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount") as "FSS_OBArrearAmount", sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") as "FSS_OBExcessAmount", sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") as "FSS_WaivedAmount", sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount") as "FSS_AdjustedAmount", sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") as "FSS_RefundAmount" FROM "dbo"."Fee_Yearly_Group_Head_Mapping" INNER JOIN "dbo"."Fee_Master_Head" ON "dbo"."Fee_Yearly_Group_Head_Mapping"."FMH_Id" = "dbo"."Fee_Master_Head"."FMH_Id" INNER JOIN "dbo"."Fee_Master_Terms_FeeHeads" ON "dbo"."Fee_Master_Head"."FMH_Id" = "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" INNER JOIN "dbo"."Fee_Student_Status" INNER JOIN "dbo"."Adm_M_Student" ON "dbo"."Fee_Student_Status"."AMST_Id" = "dbo"."Adm_M_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_Y_Student" ON "dbo"."Adm_M_Student"."AMST_Id" = "dbo"."Adm_School_Y_Student"."AMST_Id" INNER JOIN "dbo"."Adm_School_M_Class" ON "dbo"."Adm_School_Y_Student"."ASMCL_Id" = "dbo"."Adm_School_M_Class"."ASMCL_Id" INNER JOIN "dbo"."Adm_School_M_Section" ON "dbo"."Adm_School_Y_Student"."ASMS_Id" = "dbo"."Adm_School_M_Section"."ASMS_Id" ON "dbo"."Fee_Master_Terms_FeeHeads"."FMH_Id" = "dbo"."Fee_Student_Status"."FMH_Id" AND "dbo"."Fee_Master_Terms_FeeHeads"."FTI_Id" = "dbo"."Fee_Student_Status"."FTI_Id" inner join "trn"."TR_Student_Route" on  "trn"."TR_Student_Route"."AMST_Id"="dbo"."Fee_Student_Status"."AMST_Id" WHERE ("dbo"."Adm_School_Y_Student"."ASMAY_Id" = ' || "asmay_id" || ') and ("dbo"."Fee_Student_Status"."MI_Id"=' || "mi_id" || ') ' || "sql1" || '   AND ("dbo"."Fee_Master_Terms_FeeHeads"."FMT_Id" IN (' || "fmt_ids" || ')) and ("trn"."TR_Student_Route"."TRMR_Id"=' || "trmr_id" || ')  ' || "amst_sol" || ' ' || "sql2" || '   group by "ASMCL_ClassName","ASMC_SectionName","AMST_FirstName","AMST_MiddleName","AMST_LastName" having sum("dbo"."Fee_Student_Status"."FSS_OBArrearAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_OBExcessAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_WaivedAmount") >0 or sum("dbo"."Fee_Student_Status"."FSS_AdjustedAmount")>0 or sum("dbo"."Fee_Student_Status"."FSS_RefundAmount") >0';
        END IF;
    ELSE
        IF "details" = 'WO' THEN
            "query" := 'select (COALESCE("dbo"."Adm_M_Student"."AMST_FirstName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_MiddleName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_LastName",'''')) "StudentName", "dbo"."Adm_School_M_Class"."ASMCL_ClassName" || '':'' || "dbo"."Adm_School_M_Section"."ASMC_SectionName" as "ASMCL_ClassName","FSWO_WaivedOffAmount","Fee_Master_Head"."FMH_FeeName","FSS_PaidAmount","FSS_ToBePaid","FSS_TotalToBePaid",to_char("FSWO_Date",''DD/MM/YYYY'') "FSWO_Date" from "Fee_Student_Status" inner join "Fee_Student_Waived_Off" on "Fee_Student_Waived_Off"."AMST_Id"="Fee_Student_Status"."AMST_Id" and "Fee_Student_Waived_Off"."FMH_Id"="Fee_Student_Status"."FMH_Id" and "Fee_Student_Waived_Off"."fti_id"="Fee_Student_Status"."FTI_Id" and "Fee_Student_Waived_Off"."fmg_id"="Fee_Student_Status"."FMG_Id" inner join "Adm_School_Y_Student" on "Fee_Student_Status"."AMST_Id"="Adm_School_Y_Student"."AMST_Id" inner join "Adm_School_M_Class" on   "Adm_School_M_Class"."ASMCL_Id"="Adm_School_Y_Student"."ASMCL_Id" inner join "Adm_School_M_Section" on "Adm_School_M_Section"."ASMS_Id"="Adm_School_Y_Student"."ASMS_Id" inner join "Adm_M_Student" on "Adm_M_Student"."AMST_Id"="Adm_School_Y_Student"."AMST_Id" inner join "Fee_Master_Head" on "Fee_Master_Head"."FMH_Id"="Fee_Student_Status"."FMH_Id" where "Fee_Student_Waived_Off"."MI_Id"=' || "mi_id" || ' ' || "sql2" || ' ' || "sql1" || ' and "Fee_Student_Waived_Off"."ASMAY_Id"=' || "asmay_id" || ' ' || "amst_sol" || ' ';
        ELSIF "details" = 'OB' THEN
            "query" := 'select distinct (COALESCE("dbo"."Adm_M_Student"."AMST_FirstName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_MiddleName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_LastName",'''')) "StudentName", "dbo"."Adm_School_M_Class"."ASMCL_ClassName" || '':'' || "dbo"."Adm_School_M_Section"."ASMC_SectionName" as "ASMCL_ClassName", "Fee_Master_Head"."FMH_FeeName","FMOB_Student_Due","FMOB_Institution_Due","FSS_PaidAmount","FSS_ToBePaid","FSS_TotalToBePaid",to_char("FMOB_EntryDate",''DD/MM/YYYY'') "FSWO_Date" from "Fee_Student_Status" inner join "Fee_Master_Opening_Balance" on "Fee_Master_Opening_Balance"."AMST_Id"="Fee_Student_Status"."AMST_Id" and "Fee_Master_Opening_Balance"."FMH_Id"="Fee_Student_Status"."FMH_Id" and "Fee_Master_Opening_Balance"."fti_id"="Fee_Student_Status"."FTI_Id" and "Fee_Master_Opening_Balance"."fmg_id"="Fee_Student_Status"."FMG_Id" inner join "Adm_School_Y_Student" on "Fee_Student_Status"."AMST_Id"="Adm_School_Y_Student"."AMST_Id" inner join "Adm_School_M_Class" on "Adm_School_M_Class"."ASMCL_Id"="Adm_School_Y_Student"."ASMCL_Id" inner join "Adm_School_M_Section" on "Adm_School_M_Section"."ASMS_Id"="Adm_School_Y_Student"."ASMS_Id" inner join "Adm_M_Student" on "Adm_M_Student"."AMST_Id"="Adm_School_Y_Student"."AMST_Id" inner join "Fee_Master_Head" on "Fee_Master_Head"."FMH_Id"="Fee_Student_Status"."FMH_Id" where "Fee_Master_Opening_Balance"."MI_Id"=' || "mi_id" || ' ' || "sql2" || ' ' || "sql1" || ' and "Fee_Master_Opening_Balance"."ASMAY_Id"=' || "asmay_id" || ' ' || "amst_sol" || ' ';
        ELSIF "details" = 'AA' THEN
            "query" := 'select (COALESCE("dbo"."Adm_M_Student"."AMST_FirstName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_MiddleName",'''') || '' '' || COALESCE("dbo"."Adm_M_Student"."AMST_LastName",'''')) "StudentName", "dbo"."Adm