CREATE OR REPLACE FUNCTION "dbo"."CalculateRoundOffValue"(
    "CALCULATIONAMOUNT" DECIMAL(18,2), 
    "ROUNDUPCATEGORY" VARCHAR(50),
    OUT "ROUNDUPVALUE" DECIMAL(18,2)
)
RETURNS DECIMAL(18,2)
LANGUAGE plpgsql
AS $$
DECLARE
    "FIRSTDECIMALVALUE" INT;
    "NEXTDECIMALVALUE" INT;
    "FIRSTVARCHARVALUE" VARCHAR(50);
    "FIRSTBOOLCHARVALUE" BOOLEAN;
    "result3" BIGINT;
    "LastValue" BIGINT;
BEGIN
    "FIRSTVARCHARVALUE" := SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR)) - 1);

    IF "FIRSTVARCHARVALUE" = '-0' THEN
        "FIRSTBOOLCHARVALUE" := TRUE;
    ELSE
        "FIRSTBOOLCHARVALUE" := FALSE;
    END IF;

    "FIRSTDECIMALVALUE" := CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR)) - 1) AS INT);
    "NEXTDECIMALVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR)) + 1, 1) AS DECIMAL), 2);

    IF "ROUNDUPCATEGORY" = 'RoundUp' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            "ROUNDUPVALUE" := 0;
        ELSIF "FIRSTDECIMALVALUE" >= 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) + 1;
            ELSIF "NEXTDECIMALVALUE" = 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) + 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) + 1;
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            ELSIF "NEXTDECIMALVALUE" = 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'HalfRoundUp' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            IF "NEXTDECIMALVALUE" <= 5 THEN
                "ROUNDUPVALUE" := 0;
            ELSE
                "ROUNDUPVALUE" := -1;
            END IF;
        ELSIF "FIRSTDECIMALVALUE" >= 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) + 1;
            ELSE
                "ROUNDUPVALUE" := CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR)) - 1) AS DECIMAL);
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) - 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'RoundDown' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            "ROUNDUPVALUE" := -1;
        ELSIF "FIRSTDECIMALVALUE" >= 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            ELSIF "NEXTDECIMALVALUE" = 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) - 1;
            ELSIF "NEXTDECIMALVALUE" = 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) - 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) - 1;
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'HalfRoundDown' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := -1;
            ELSE
                "ROUNDUPVALUE" := 0;
            END IF;
        ELSIF "FIRSTDECIMALVALUE" >= 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) + 1;
            ELSE
                "ROUNDUPVALUE" := CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR)) - 1) AS DECIMAL);
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) - 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'RoundTowardsZero' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            "ROUNDUPVALUE" := 0;
        ELSIF "FIRSTDECIMALVALUE" >= 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'RoundAwayFromZero' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            "ROUNDUPVALUE" := -1;
        ELSIF "FIRSTDECIMALVALUE" >= 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) + 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) + 1;
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) - 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) - 1;
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'Roundhalftowardszero' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            IF "NEXTDECIMALVALUE" <= 5 THEN
                "ROUNDUPVALUE" := 0;
            ELSE
                "ROUNDUPVALUE" := -1;
            END IF;
        ELSIF "FIRSTDECIMALVALUE" >= 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) + 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) - 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'Roundhalfawayfromzero' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := -1;
            ELSE
                "ROUNDUPVALUE" := 0;
            END IF;
        ELSIF "FIRSTDECIMALVALUE" >= 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) + 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2) - 1;
            ELSE
                "ROUNDUPVALUE" := ROUND(CAST(SUBSTRING(CAST("CALCULATIONAMOUNT" AS VARCHAR), 1, POSITION('.' IN CAST("CALCULATIONAMOUNT" AS VARCHAR))) AS DECIMAL), 2);
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'Roundhalftoeven' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := -1;
            ELSE
                "ROUNDUPVALUE" := 0;
            END IF;
        ELSIF "FIRSTDECIMALVALUE" > 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE" + 1;
            ELSE
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE";
            END IF;
        ELSIF "FIRSTDECIMALVALUE" = 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE" + 1;
            ELSE
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE";
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE" - 1;
            ELSE
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE";
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'Roundhalftoodd' THEN
        IF "FIRSTBOOLCHARVALUE" = TRUE THEN
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := -1;
            ELSE
                "ROUNDUPVALUE" := 0;
            END IF;
        ELSIF "FIRSTDECIMALVALUE" > 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE" + 1;
            ELSE
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE";
            END IF;
        ELSIF "FIRSTDECIMALVALUE" = 0 AND "FIRSTBOOLCHARVALUE" = FALSE THEN
            IF "NEXTDECIMALVALUE" >= 5 THEN
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE" + 1;
            ELSE
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE";
            END IF;
        ELSE
            IF "NEXTDECIMALVALUE" > 5 THEN
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE" - 1;
            ELSE
                "ROUNDUPVALUE" := "FIRSTDECIMALVALUE";
            END IF;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'Floor' THEN
        "ROUNDUPVALUE" := FLOOR("CALCULATIONAMOUNT");

    ELSIF "ROUNDUPCATEGORY" = 'Ceiling' THEN
        "ROUNDUPVALUE" := CEILING("CALCULATIONAMOUNT");

    ELSIF "ROUNDUPCATEGORY" = 'Rounduptohundredths' THEN
        "ROUNDUPVALUE" := ROUND(CAST("CALCULATIONAMOUNT" AS NUMERIC), 2);

    ELSIF "ROUNDUPCATEGORY" = 'Rounduptotens' THEN
        "ROUNDUPVALUE" := ROUND(CAST("CALCULATIONAMOUNT" AS NUMERIC), 1);

    ELSIF "ROUNDUPCATEGORY" = 'Rounduptowardsnextten' THEN
        SELECT "dbo"."CalculateRoundOffValue"("CALCULATIONAMOUNT", 'RoundDown') INTO "result3";
        "LastValue" := RIGHT("result3"::TEXT, 1)::BIGINT;
        IF "LastValue" > 0 THEN
            "result3" := "result3" - "LastValue";
            "ROUNDUPVALUE" := "result3" + 10;
        END IF;

    ELSIF "ROUNDUPCATEGORY" = 'Roundupnearestten' THEN
        SELECT "dbo"."CalculateRoundOffValue"("CALCULATIONAMOUNT", 'RoundDown') INTO "result3";
        "LastValue" := RIGHT("result3"::TEXT, 1)::BIGINT;
        IF "LastValue" >= 1 AND "LastValue" <= 4 THEN
            "result3" := "result3" - "LastValue";
        ELSIF "LastValue" >= 5 AND "LastValue" <= 9 THEN
            "result3" := "result3" - "LastValue";
            "result3" := "result3" + 10;
        END IF;
        "ROUNDUPVALUE" := "result3";

    ELSE
        "ROUNDUPVALUE" := ROUND(CAST("CALCULATIONAMOUNT" AS NUMERIC), 0);
    END IF;

    RAISE NOTICE 'ROUNDUPVALUE: %', "ROUNDUPVALUE";
    RETURN;
END;
$$;